/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ays.gui;

import ays.database.ArizaKaydiIslemleri;
import ays.database.MakinaIslemleri;
import ays.database.PersonelIslemleri;
import ays.modeller.ArizaKaydi;
import ays.modeller.Personel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author begum.celebi
 */
public class ArızaKayıtAra extends javax.swing.JFrame {

    private static MakinaIslemleri makinaIslemleri;
    private static ArizaKaydiIslemleri arizaKaydiIslemleri;
    private static PersonelIslemleri personelIslemleri;

    /**
     * Creates new form Tamamlanan
     */
    public ArızaKayıtAra() {
        initComponents();

        arizaNoAraTextField.setFormatterFactory(new JFormattedTextField.AbstractFormatterFactory() {
            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField tf) {
                NumberFormat format = NumberFormat.getInstance();
                NumberFormatter formatter = new NumberFormatter(format);
                formatter.setValueClass(Integer.class);
                formatter.setMinimum(0);
                formatter.setMaximum(Integer.MAX_VALUE);
                formatter.setAllowsInvalid(false);
                return formatter;
            }
        });

        Dimension dim;
        dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        makinaIslemleri = new MakinaIslemleri();
        arizaKaydiIslemleri = new ArizaKaydiIslemleri();
        personelIslemleri = new PersonelIslemleri();
        ArrayList<Personel> teknisyenler = personelIslemleri.TeknisyenleriGetir();

        for (Personel personel : teknisyenler) {
            teknisyenComboBox1.addItem(personel.getSicilNo());
        }

        bolumComboBox.setEnabled(false);
        hatComboBox.setEnabled(false);
        makineComboBox.setEnabled(false);
        arizaNoAraTextField.setEnabled(false);
        arizaAraTanimTextField.setEnabled(false);
        teknisyenComboBox1.setEnabled(false);
        hatCheckBox.setEnabled(false);
        makineCheckBox.setEnabled(false);

        aramaSonucTablo.setVisible(false);

        bolumComboBoxActionPerformed(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bolumComboBox = new javax.swing.JComboBox<>();
        hatComboBox = new javax.swing.JComboBox<>();
        makineComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        arizaAraTanimTextField = new javax.swing.JTextField();
        arizaAraButon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sonucGosterComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aramaSonucTablo = new javax.swing.JTable();
        geriButon = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        toplamKayitLabel = new javax.swing.JLabel();
        teknisyenComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        bolumCheckBox = new javax.swing.JCheckBox();
        hatCheckBox = new javax.swing.JCheckBox();
        makineCheckBox = new javax.swing.JCheckBox();
        arizaNoCheckBox = new javax.swing.JCheckBox();
        arizaTanimCheckBox = new javax.swing.JCheckBox();
        teknisyenCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        arizaNoAraTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arıza Kayıt Arama");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Arıza Arama ");
        jLabel1.setMaximumSize(new java.awt.Dimension(175, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Bölüm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Makine");

        bolumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastik", "Oto Dizgi", "Manuel Dizgi" }));
        bolumComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolumComboBoxActionPerformed(evt);
            }
        });

        hatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Arıza No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Arıza Tanımı");

        arizaAraButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        arizaAraButon.setText("Ara");
        arizaAraButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaAraButonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sonuçlar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Son");

        sonucGosterComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sonucGosterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "25", "50" }));
        sonucGosterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucGosterComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("göster");

        aramaSonucTablo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        aramaSonucTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(aramaSonucTablo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sonucGosterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonucGosterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        geriButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geriButon.setText("GERİ");
        geriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButonActionPerformed(evt);
            }
        });

        jLabel13.setText("Terim girin");

        jLabel14.setText("Toplam kayıt:");

        teknisyenComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teknisyenComboBox1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Teknisyen");

        jCheckBox1.setText("jCheckBox1");

        bolumCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolumCheckBoxActionPerformed(evt);
            }
        });

        hatCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatCheckBoxActionPerformed(evt);
            }
        });

        makineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makineCheckBoxActionPerformed(evt);
            }
        });

        arizaNoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaNoCheckBoxActionPerformed(evt);
            }
        });

        arizaTanimCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaTanimCheckBoxActionPerformed(evt);
            }
        });

        teknisyenCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teknisyenCheckBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Filtreleme yapmak istediğiniz alanları işaretleyin.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bolumCheckBox)
                        .addComponent(hatCheckBox))
                    .addComponent(makineCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(bolumComboBox, 0, 166, Short.MAX_VALUE)
                            .addComponent(hatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makineComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(arizaNoCheckBox)
                            .addComponent(arizaTanimCheckBox)
                            .addComponent(teknisyenCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(arizaAraTanimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13))
                                    .addComponent(arizaNoAraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jCheckBox1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(arizaAraButon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(59, 59, 59)
                                            .addComponent(teknisyenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addContainerGap(940, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geriButon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toplamKayitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geriButon)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bolumCheckBox)
                            .addComponent(bolumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hatCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(makineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makineCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arizaNoCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(arizaNoAraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(arizaAraTanimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(arizaTanimCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(teknisyenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teknisyenCheckBox))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(arizaAraButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toplamKayitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jCheckBox1)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arizaAraButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaAraButonActionPerformed
        aramaSonucTablo.removeAll();

        ArrayList<ArizaKaydi> aramaSonucListe = new ArrayList<>();

        if (arizaNoCheckBox.isEnabled() && arizaNoCheckBox.isSelected()) {

            String number = arizaNoAraTextField.getText();
            if (!number.isEmpty()) {
                number = number.replaceAll("\\.", "");
            }
            ArizaKaydi arizaKaydi = arizaKaydiIslemleri.ArizaKaydiGetir(Integer.parseInt(number));
            if (arizaKaydi != null) {
                aramaSonucListe.add(arizaKaydi);
            }
        } else {

            String bolum = "", hat = "", makina = "", arizaText = "", teknisyenSicilNo = "";

            if (bolumCheckBox.isEnabled() && bolumCheckBox.isSelected()) {
                bolum = bolumComboBox.getSelectedItem().toString();
            }

            if (hatCheckBox.isEnabled() && hatCheckBox.isSelected()) {
                hat = hatComboBox.getSelectedItem().toString();
            }

            if (makineCheckBox.isEnabled() && makineCheckBox.isSelected()) {
                makina = makineComboBox.getSelectedItem().toString();
            }

            if (arizaTanimCheckBox.isEnabled() && arizaTanimCheckBox.isSelected()) {
                arizaText = arizaAraTanimTextField.getText();
            }

            if (teknisyenCheckBox.isEnabled() && teknisyenCheckBox.isSelected() && teknisyenComboBox1.getSelectedItem() != null) {
                teknisyenSicilNo = teknisyenComboBox1.getSelectedItem().toString();
            }

            aramaSonucListe = arizaKaydiIslemleri.KayitleriGetir(bolum, hat, makina, teknisyenSicilNo, arizaText);

        }

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("AKNO");
        table.addColumn("Bölüm");
        table.addColumn("Hat");
        table.addColumn("Makina");
        table.addColumn("Arıza");
        table.addColumn("Başlangıç");
        table.addColumn("Bitiş");
        table.addColumn("Kategori");
        table.addColumn("Teknisyen");
        table.addColumn("Bildiren");
        table.addColumn("İşlem");

        for (ArizaKaydi arizaKaydi : aramaSonucListe) {
            Object[] row = new Object[11];
            row[0] = arizaKaydi.getAkno();
            row[1] = arizaKaydi.getBolum();
            row[2] = arizaKaydi.getHat();
            row[3] = arizaKaydi.getMakina();
            row[4] = arizaKaydi.getAriza();
            row[5] = arizaKaydi.getBaslangic();
            row[6] = arizaKaydi.getBitis();
            row[7] = arizaKaydi.getKategori();
            row[8] = arizaKaydi.getTeknisyen();
            row[9] = arizaKaydi.getOlusturan_sicilno();
            row[10] = arizaKaydi.getIslem();

            table.addRow(row);
        }

        aramaSonucTablo.setModel(table);

        int satirSayisi = aramaSonucTablo.getRowCount();
        toplamKayitLabel.setText(String.valueOf(satirSayisi));
        aramaSonucTablo.setVisible(true);
    }//GEN-LAST:event_arizaAraButonActionPerformed

    private void geriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButonActionPerformed
        // TODO add your handling code here:

        Anasayfa giris = new Anasayfa();
        giris.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_geriButonActionPerformed

    private void sonucGosterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucGosterComboBoxActionPerformed
        // TODO add your handling code here:
        if (sonucGosterComboBox.getSelectedItem() == "10") {

        } else if (sonucGosterComboBox.getSelectedItem() == "25") {

        } else {

        }
    }//GEN-LAST:event_sonucGosterComboBoxActionPerformed

    private void bolumComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolumComboBoxActionPerformed
        hatComboBox.removeAllItems();
        makineComboBox.removeAllItems();

        if (bolumComboBox.getSelectedItem() == null) {
            return;
        }
        ArrayList<String> makinaIsimleri = makinaIslemleri.HatIsımleriniGetir(bolumComboBox.getSelectedItem().toString());

        for (String isim : makinaIsimleri) {
            hatComboBox.addItem(isim);
        }
    }//GEN-LAST:event_bolumComboBoxActionPerformed

    private void hatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatComboBoxActionPerformed
        makineComboBox.removeAllItems();
        if (bolumComboBox.getSelectedItem() != null && hatComboBox.getSelectedItem() != null) {
            ArrayList<String> makinaIsimleri = makinaIslemleri.MakinaIsımleriniGetir(bolumComboBox.getSelectedItem().toString(), hatComboBox.getSelectedItem().toString());
            for (String isim : makinaIsimleri) {
                makineComboBox.addItem(isim);
            }
        }
    }//GEN-LAST:event_hatComboBoxActionPerformed

    private void teknisyenComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teknisyenComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_teknisyenComboBox1ActionPerformed

    private void bolumCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolumCheckBoxActionPerformed
        // TODO add your handling code here:
        hatCheckBox.setEnabled(true);

        if (bolumCheckBox.isSelected() == true) {
            bolumComboBox.setEnabled(true);
        } else {
            bolumComboBox.setEnabled(false);
        }

    }//GEN-LAST:event_bolumCheckBoxActionPerformed

    private void arizaNoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaNoCheckBoxActionPerformed
        // TODO add your handling code here:
        if (arizaNoCheckBox.isSelected() == true) {
            arizaNoAraTextField.setEnabled(true);

            bolumCheckBox.setEnabled(false);
            bolumComboBox.setEnabled(false);

            hatCheckBox.setEnabled(false);
            hatComboBox.setEnabled(false);

            makineCheckBox.setEnabled(false);
            makineComboBox.setEnabled(false);

            arizaTanimCheckBox.setEnabled(false);
            arizaAraTanimTextField.setEnabled(false);

            teknisyenCheckBox.setEnabled(false);
            teknisyenComboBox1.setEnabled(false);

        } else {
            arizaNoAraTextField.setEnabled(false);

            bolumCheckBox.setEnabled(true);
            hatCheckBox.setEnabled(true);
            makineCheckBox.setEnabled(true);
            arizaTanimCheckBox.setEnabled(true);
            teknisyenCheckBox.setEnabled(true);
        }

    }//GEN-LAST:event_arizaNoCheckBoxActionPerformed

    private void arizaTanimCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaTanimCheckBoxActionPerformed
        // TODO add your handling code here:
        if (arizaTanimCheckBox.isSelected() == true) {
            arizaAraTanimTextField.setEnabled(true);
        } else {
            arizaAraTanimTextField.setEnabled(false);
        }
    }//GEN-LAST:event_arizaTanimCheckBoxActionPerformed

    private void teknisyenCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teknisyenCheckBoxActionPerformed
        // TODO add your handling code here:
        if (teknisyenCheckBox.isSelected() == true) {
            teknisyenComboBox1.setEnabled(true);
        } else {
            teknisyenComboBox1.setEnabled(false);
        }
    }//GEN-LAST:event_teknisyenCheckBoxActionPerformed

    private void hatCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatCheckBoxActionPerformed
        // TODO add your handling code here:
        makineCheckBox.setEnabled(true);
        if (hatCheckBox.isSelected() && bolumCheckBox.isSelected() == true) {
            hatComboBox.setEnabled(true);
        } else {
            hatComboBox.setEnabled(false);
        }


    }//GEN-LAST:event_hatCheckBoxActionPerformed

    private void makineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makineCheckBoxActionPerformed
        // TODO add your handling code here:

        if (makineCheckBox.isSelected() && bolumCheckBox.isSelected() && hatCheckBox.isSelected() == true) {
            makineComboBox.setEnabled(true);
        } else {
            makineComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_makineCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aramaSonucTablo;
    private javax.swing.JButton arizaAraButon;
    private javax.swing.JTextField arizaAraTanimTextField;
    private javax.swing.JFormattedTextField arizaNoAraTextField;
    private javax.swing.JCheckBox arizaNoCheckBox;
    private javax.swing.JCheckBox arizaTanimCheckBox;
    private javax.swing.JCheckBox bolumCheckBox;
    private javax.swing.JComboBox<String> bolumComboBox;
    private javax.swing.JButton geriButon;
    private javax.swing.JCheckBox hatCheckBox;
    private javax.swing.JComboBox<String> hatComboBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox makineCheckBox;
    private javax.swing.JComboBox<String> makineComboBox;
    private javax.swing.JComboBox<String> sonucGosterComboBox;
    private javax.swing.JCheckBox teknisyenCheckBox;
    private javax.swing.JComboBox<String> teknisyenComboBox1;
    private javax.swing.JLabel toplamKayitLabel;
    // End of variables declaration//GEN-END:variables

}
