/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ays.gui;

import ays.database.ArizaKaydiIslemleri;
import ays.database.PersonelIslemleri;
import ays.database.VeritabaniBaglantiYoneticisi;
import ays.modeller.ArizaKaydi;
import ays.modeller.Personel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author begum.celebi
 */
public class ArızaKapatForm extends javax.swing.JFrame {

    private static PersonelIslemleri personelIslemleri;
    private static ArizaKaydiIslemleri arizaKaydiIslemleri;
    private static int _arizaKodu = 0;

    /**
     * Creates new form ArızaKapatForm
     *
     * @param arizaKodu
     */
    public ArızaKapatForm(int arizaKodu) {
        _arizaKodu = arizaKodu;
        initComponents();

        Dimension dim;
        dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        personelIslemleri = new PersonelIslemleri();
        arizaKaydiIslemleri = new ArizaKaydiIslemleri();

        ArizaKaydi arizaKaydi = arizaKaydiIslemleri.ArizaKaydiGetir(arizaKodu);

        jLabel13.setText(arizaKodu + "");
        jLabel14.setText(arizaKaydi.getBolum());
        jLabel15.setText(arizaKaydi.getHat());
        jLabel16.setText(arizaKaydi.getMakina());
        jLabel18.setText(arizaKaydi.getBaslangic());
        jLabel19.setText(arizaKaydi.getBitis());
        jLabel17.setText(arizaKaydi.getTeknisyen());
        jLabel23.setText(arizaKaydi.getAriza());

        ArrayList<Personel> teknisyenler = personelIslemleri.TeknisyenleriGetir();

        for (Personel personel : teknisyenler) {
            teknisyenComboBox1.addItem(personel.getSicilNo());
        }

        teknisyenComboBox1.setSelectedItem(arizaKaydi.getTeknisyen());
        kategoriComboBox4.setSelectedItem(arizaKaydi.getKategori());
        arizaYapilanIslemlerTextField.setText(arizaKaydi.getIslem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        arizaDurumPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teknisyenComboBox1 = new javax.swing.JComboBox<>();
        kategoriComboBox4 = new javax.swing.JComboBox<>();
        arizaKapatButonu = new javax.swing.JButton();
        degisiklikKaydetButon = new javax.swing.JButton();
        arizaYapilanIslemlerTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        arizaBilgiPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        geriButon = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arıza Güncelle");

        arizaDurumPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kategori");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Arıza Durum Formu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Yapılan İşlemler");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Teknisyen");

        kategoriComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mekanik / Elektronik", "Program / Bilgisayar", "Feeder / RoadRunner", "Diğer" }));

        arizaKapatButonu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        arizaKapatButonu.setText("Arızayı Kapat");
        arizaKapatButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaKapatButonuActionPerformed(evt);
            }
        });

        degisiklikKaydetButon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        degisiklikKaydetButon.setText("Değişiklikleri Kaydet");
        degisiklikKaydetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degisiklikKaydetButonActionPerformed(evt);
            }
        });

        arizaYapilanIslemlerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaYapilanIslemlerTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setText("(Arıza açık kalır)");

        javax.swing.GroupLayout arizaDurumPanelLayout = new javax.swing.GroupLayout(arizaDurumPanel);
        arizaDurumPanel.setLayout(arizaDurumPanelLayout);
        arizaDurumPanelLayout.setHorizontalGroup(
            arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                        .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teknisyenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(arizaYapilanIslemlerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                        .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kategoriComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arizaDurumPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(arizaKapatButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(degisiklikKaydetButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))))
        );
        arizaDurumPanelLayout.setVerticalGroup(
            arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arizaYapilanIslemlerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(arizaDurumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degisiklikKaydetButon)
                        .addComponent(jLabel22))
                    .addGroup(arizaDurumPanelLayout.createSequentialGroup()
                        .addComponent(teknisyenComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kategoriComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(7, 7, 7)
                .addComponent(arizaKapatButonu)
                .addContainerGap())
        );

        arizaBilgiPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Arıza No      : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Bölüm          : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Başlangıç    :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Teknisyen  : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Hat               :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Makine        :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Bitiş              :");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel15.setText("jLabel15");

        jLabel16.setText("jLabel16");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel19.setText("jLabel19");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Arıza Bilgi");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Açıklama     :");

        jLabel23.setText("Açıklama Yok!");

        javax.swing.GroupLayout arizaBilgiPanelLayout = new javax.swing.GroupLayout(arizaBilgiPanel);
        arizaBilgiPanel.setLayout(arizaBilgiPanelLayout);
        arizaBilgiPanelLayout.setHorizontalGroup(
            arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(240, 240, 240))
            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                        .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addGap(69, 69, 69)))
                        .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        arizaBilgiPanelLayout.setVerticalGroup(
            arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arizaBilgiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(arizaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        geriButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geriButon.setText("GERİ");
        geriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(geriButon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(arizaDurumPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arizaBilgiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geriButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arizaBilgiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arizaDurumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButonActionPerformed
        // TODO add your handling code here:

        Onarımdakiler onarımdakiler = new Onarımdakiler();
        onarımdakiler.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_geriButonActionPerformed

    private void arizaYapilanIslemlerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaYapilanIslemlerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arizaYapilanIslemlerTextFieldActionPerformed

    private String getCurrentDate() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        String tarih = df.format(new Date());

        return tarih;
    }

    private void degisiklikKaydetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degisiklikKaydetButonActionPerformed
        //Onarımdakiler onarımTabloNesnesi= new Onarımdakiler();
        Connection baglanti;
        int secim = JOptionPane.showConfirmDialog(null, "Arızayı güncellemek istiyor musunuz?", " ", JOptionPane.YES_NO_OPTION);
        try {
            baglanti = VeritabaniBaglantiYoneticisi.getConnection();
            Statement sorgu;
            sorgu = baglanti.createStatement();
            if (secim == 0) {  // yes = 0   no= 1
                sorgu.executeUpdate("UPDATE ariza_kaydi SET islem =" + "'" + arizaYapilanIslemlerTextField.getText() + "', "
                        + " teknisyen = '" + teknisyenComboBox1.getSelectedItem().toString() + "', "
                        + " kategori = '" + kategoriComboBox4.getSelectedItem().toString() + "' "
                        + " WHERE akno=" + _arizaKodu + "");
                JOptionPane.showMessageDialog(null, "Değişiklikler Kaydedildi", "", JOptionPane.PLAIN_MESSAGE);

                Onarımdakiler onarımdakiler = new Onarımdakiler();
                onarımdakiler.show();
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(YeniArızaKaydı.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_degisiklikKaydetButonActionPerformed

    private void arizaKapatButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaKapatButonuActionPerformed
        // TODO add your handling code here:
        //Onarımdakiler onarımTabloNesnesi= new Onarımdakiler();
        Connection baglanti;
        int secim = JOptionPane.showConfirmDialog(null, "Arızayı kapatmak istiyor musunuz?", " ", JOptionPane.YES_NO_OPTION);
        try {
            baglanti = VeritabaniBaglantiYoneticisi.getConnection();
            Statement sorgu;
            sorgu = baglanti.createStatement();
            if (secim == 0) {  // yes = 0   no= 1

                String islemler = arizaYapilanIslemlerTextField.getText();

                sorgu.executeUpdate("UPDATE ariza_kaydi SET islem =" + "'"
                        + arizaYapilanIslemlerTextField.getText() + "'," + " bitis =" + "'" + getCurrentDate() + "'"
                        + "WHERE akno=" + _arizaKodu + "");

                JOptionPane.showMessageDialog(null, "Arıza kapatıldı", "", JOptionPane.PLAIN_MESSAGE);

                Onarımdakiler onarımdakiler = new Onarımdakiler();
                onarımdakiler.show();
                this.dispose();
            }

        } catch (SQLException ex) {
            Logger.getLogger(YeniArızaKaydı.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_arizaKapatButonuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arizaBilgiPanel;
    private javax.swing.JPanel arizaDurumPanel;
    private javax.swing.JButton arizaKapatButonu;
    private javax.swing.JTextField arizaYapilanIslemlerTextField;
    private javax.swing.JButton degisiklikKaydetButon;
    private javax.swing.JButton geriButon;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> kategoriComboBox4;
    private javax.swing.JComboBox<String> teknisyenComboBox1;
    // End of variables declaration//GEN-END:variables

}
