/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ays.gui;

import ays.database.ArizaKaydiIslemleri;
import ays.database.MakinaIslemleri;
import ays.modeller.ArizaKaydi;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author begum.celebi
 */
public class YeniArızaKaydı extends javax.swing.JFrame {

    private static MakinaIslemleri makinaIslemleri;
    private static ArizaKaydiIslemleri arizaKaydiIslemleri;

    /**
     * Creates new form YeniArızaKaydı
     */
    public YeniArızaKaydı() {
        initComponents();

        makinaIslemleri = new MakinaIslemleri();
        arizaKaydiIslemleri = new ArizaKaydiIslemleri();

        if (!GirisYapmisKullanici.kullanici.getSicilNo().equals("0")) {
            sicilTextField.setText(GirisYapmisKullanici.kullanici.getSicilNo());
            sicilTextField.setEnabled(false);
        }

        bolumComboBoxActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        geriButon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hatComboBox = new javax.swing.JComboBox<>();
        arizaBildirButon = new javax.swing.JButton();
        makineComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        kategoriComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sicilTextField = new javax.swing.JTextField();
        bolumComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arizaTextArea = new javax.swing.JTextArea();
        btnIptal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arıza Bildirim Formu");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Arıza Bildirim Formu");
        jLabel1.setMaximumSize(new java.awt.Dimension(175, 22));

        geriButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        geriButon.setText("GERİ");
        geriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hat Seçiniz");

        hatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatComboBoxActionPerformed(evt);
            }
        });

        arizaBildirButon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        arizaBildirButon.setText("Arıza Bildir");
        arizaBildirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arizaBildirButonActionPerformed(evt);
            }
        });

        makineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Makine Seçiniz");

        kategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mekanik-Elektronik", "Program-Bilgisayar", "Feeder-RoadRunner", "Diğer" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Kategori Seçiniz");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sicilinizi Girin");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bölüm Seçiniz");

        sicilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicilTextFieldActionPerformed(evt);
            }
        });

        bolumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastik", "Oto Dizgi", "Manuel Dizgi" }));
        bolumComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolumComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Arıza Detayını Girin");

        arizaTextArea.setColumns(20);
        arizaTextArea.setRows(5);
        jScrollPane1.setViewportView(arizaTextArea);

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(bolumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sicilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIptal)
                .addGap(18, 18, 18)
                .addComponent(arizaBildirButon)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bolumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sicilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(makineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arizaBildirButon)
                    .addComponent(btnIptal))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geriButon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geriButon)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Anasayfa giris = new Anasayfa();
        giris.setVisible(true);
    }//GEN-LAST:event_geriButonActionPerformed

    private void bolumComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolumComboBoxActionPerformed

        hatComboBox.removeAllItems();
        makineComboBox.removeAllItems();

        ArrayList<String> makinaIsimleri = makinaIslemleri.HatIsımleriniGetir(bolumComboBox.getSelectedItem().toString());

        for (String isim : makinaIsimleri) {
            hatComboBox.addItem(isim);
        }
    }//GEN-LAST:event_bolumComboBoxActionPerformed

    private void hatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatComboBoxActionPerformed
        makineComboBox.removeAllItems();

        if (bolumComboBox.getSelectedItem() != null && hatComboBox.getSelectedItem() != null) {
            ArrayList<String> makinaIsimleri = makinaIslemleri.MakinaIsımleriniGetir(bolumComboBox.getSelectedItem().toString(), hatComboBox.getSelectedItem().toString());
            for (String isim : makinaIsimleri) {
                makineComboBox.addItem(isim);
            }
        }


    }//GEN-LAST:event_hatComboBoxActionPerformed

    private String AlanlariKontrolEt() {

        if (bolumComboBox.getSelectedItem() == null || bolumComboBox.getSelectedItem().toString().isEmpty()) {
            return "Bolüm seçiniz!";
        }

        if (hatComboBox.getSelectedItem() == null || hatComboBox.getSelectedItem().toString().isEmpty()) {
            return "Hat seçiniz!";
        }

        if (kategoriComboBox.getSelectedItem() == null || kategoriComboBox.getSelectedItem().toString().isEmpty()) {
            return "Kategori seçiniz!";
        }

        if (sicilTextField.getText().isEmpty()) {
            return "Sicil no giriniz!";
        }

        if (arizaTextArea.getText().isEmpty()) {
            return "Ariza alanı giriniz!";
        }

        return null;
    }

    private void arizaBildirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arizaBildirButonActionPerformed

        String uyari = AlanlariKontrolEt();
        if (uyari != null) {
            JOptionPane.showMessageDialog(null, uyari, "Hata", JOptionPane.PLAIN_MESSAGE);
            return;
        }

        //TODO - kontroller yapılmalı
        ArizaKaydi arizaKaydi = new ArizaKaydi();
        arizaKaydi.setAriza(arizaTextArea.getText());
        arizaKaydi.setBolum(bolumComboBox.getSelectedItem().toString());
        arizaKaydi.setHat(hatComboBox.getSelectedItem().toString());
        arizaKaydi.setMakina(makineComboBox.getSelectedItem().toString());
        arizaKaydi.setKategori(kategoriComboBox.getSelectedItem().toString());
        arizaKaydi.setBitis("");
        arizaKaydi.setBaslangic(getCurrentDate());
        arizaKaydi.setTeknisyen("");
        arizaKaydi.setIslem("");
        arizaKaydi.setOlusturan_sicilno(sicilTextField.getText());
        boolean sonuc = arizaKaydiIslemleri.ArizaKaydiEkle(arizaKaydi);

        if (sonuc) {
            JOptionPane.showMessageDialog(null, "Arıza bildirildi", "", JOptionPane.PLAIN_MESSAGE);
            Anasayfa anasayfa = new Anasayfa();
            anasayfa.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_arizaBildirButonActionPerformed

    private String getCurrentDate() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        String tarih = df.format(new Date());

        return tarih;
    }

    private void sicilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicilTextFieldActionPerformed
        // TODO add your handling code here:
        String sicilNo = sicilTextField.getText();
    }//GEN-LAST:event_sicilTextFieldActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        Anasayfa anasayfa = new Anasayfa();
        anasayfa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YeniArızaKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YeniArızaKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YeniArızaKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YeniArızaKaydı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new YeniArızaKaydı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arizaBildirButon;
    private javax.swing.JTextArea arizaTextArea;
    private javax.swing.JComboBox<String> bolumComboBox;
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton geriButon;
    private javax.swing.JComboBox<String> hatComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategoriComboBox;
    private javax.swing.JComboBox<String> makineComboBox;
    private javax.swing.JTextField sicilTextField;
    // End of variables declaration//GEN-END:variables

}
